# Generated by Django 3.0.3 on 2020-02-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ministry',
        ),
    ]
