# Generated by Django 2.2.3 on 2019-11-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0002_auto_20191120_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Volunteer',
        ),
    ]
