:: run this script to install needed packages and modules
ECHO Installing Django...
pip install django 

ECHO Installing Django REST Framework...
pip install djangorestframework

ECHO Installing python module for PostgreSQL...
pip install psycopg2

ECHO Installing NPM packages...
npm install 